# This is a basic workflow to help you get started with Actions

name: OSSIBOT Audit
inputs: 
  OSSIEBOT_ID:
    required: true
runs:
  using: composite
  steps: 
    # Install OssiBOT
    - name: install ossie bot client
      run: pip3 install ossie
      shell: bash

    # Audit the Repository
    - name: Audit project dependencies
      run: |
        ossie audit --id ${{ inputs.OSSIEBOT_ID }} --project ${{ github.workspace }}
        echo 'ISSUE_REQUIRED=$(cat /temp/issue_required)' >> $GITHUB_ENV
	echo 'ISSUE_TITLE=$(cat /temp/issue_title)' >> $GITHUB_ENV
	echo 'ISSUE_BODY=$(cat /temp/issue_body)' >> $GITHUB_ENV	
      shell: bash

    - name: create issue if ISSUE_REQUIRED is set
      if: ${{ env.ISSUE_REQUIRED }} == YES
      uses: rishabhgupta/git-action-issue@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
	title: ${{ env.ISSUE_TITLE }}
	body: ${{ env.ISSUE_BODY }}