# This is a basic workflow to help you get started with Actions

name: OSSIBOT Audit
inputs: 
  OSSIEBOT_ID:
    required: true
runs:
  using: composite
  steps: 
        # Install OssiBOT
    - name: install ossie bot client
      run: pip3 install ossie
      shell: bash

#     # Audit the Repository
    - name: Audit project dependencies
      #run: ossie audit --id ${{ inputs.OSSIEBOT_ID }} --project ${{ github.workspace }}
      run: python3 setenv.py
      shell: bash

    - name: check env variable
      run: echo ${{ env.HELLO }}
      shell: bash